---

# buggy version of libvirt. 
# https://bugzilla.redhat.com/show_bug.cgi?id=1742877
# problem 
# libvirt.libvirtError: Requested operation is not valid: Setting different SELinux label on /var/lib/libvirt/images/gateway.lab.example.com.qcow2 which is already in use
# fix
# echo "remember_owner = 0" >>  /etc/libvirt/qemu.conf

- name: start the VM
  community.libvirt.virt:
    name: "{{ fqdn }}"
    state: running

# check
# These tasks use libvirt only.
# They don't check anything at the OS level, such as waiting for a connection. 

- name: get domain info
  community.libvirt.virt:
    name: "{{ fqdn }}"
    command: info
  register: r_domain_info

- name: display domain info
  ansible.builtin.debug:
    var: r_domain_info[fqdn]

# something wrong here, its not waiting
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_connection_module.html
- name: "Wait for {{ inventory_hostname }} to be ready"
  ansible.builtin.wait_for_connection:
    delay: 30
    timeout: 120
  become: no
