---

# buggy version of libvirt. 
# https://bugzilla.redhat.com/show_bug.cgi?id=1742877
# problem 
# libvirt.libvirtError: Requested operation is not valid: Setting different SELinux label on /var/lib/libvirt/images/gateway.lab.example.com.qcow2 which is already in use
# fix
# echo "remember_owner = 0" >>  /etc/libvirt/qemu.conf

# !!! risky mix of fqdn and inventory_hostname

- name: "Start VM {{ fqdn }}"
  community.libvirt.virt:
    name: "{{ fqdn }}"
    state: running

# check
# These tasks use libvirt only.
# They don't check anything at the OS level, such as waiting for a connection. 

- name: "Get domain info for {{ fqdn }}"
  community.libvirt.virt:
    name: "{{ fqdn }}"
    command: info
  register: r_domain_info

- name: display domain info
  ansible.builtin.debug:
    var: r_domain_info[fqdn]

# These tasks are delegated to hypervisor. 
# That's no good here. 
# We're not interested in the hypervisor being pingable. 
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_connection_module.html
- name: "wait for VM {{ inventory_hostname }} to respond to a ping"
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 120
  become: no
  delegate_to: "{{ inventory_hostname }}"
