---
# tasks file 
- name: install packages
  ansible.builtin.yum: 
    name: 
    - haproxy
    state: latest 

- name: Start and enable service httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: started

- name: Copy configuration
  ansible.builtin.template:
    src: index.html.j2
    dest: "/var/www/{{ apache_host }}/index.html"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0664'

