---
# defaults file for ansible-target
managed_node_user: ansible_user
managed_node_group: ansible_user
# This isn't a real key. 
# Generate a new pair, replace these values, and encrypt this file.
managed_node_public_key: |
  ssh-rsa AcKsCbRrsELO/+dLZCi4H+TWcWNm3Z0/ZyxZO8+fJpxx0PFm3F2qDS/8Ld+7CO2Yiy6MGEVrnQnmYWb+AB/djbzh/YFHl5VXsLCH7UIucY5FT2KcIVCWh/vDX4CBjWyAU4TdOjgdpQJ95YfOnny8pFaZNmJxkqUYqqEU7tmzIzLnJlZWfqxlHJuahmVofyUF8ODGsRP/NvFmJBSV5sTB4m9zqYpROXGDHBuF/DAHVDpkXpadvXqiRVcsZxCsOjqwFATtFWIzapC/Wlt0e0Buo/7rhx+tpPdwslmXIdGO1IaqN6+HQ9yjqL7IIVITfNt3Vb8ZBb1IulDcPgbei+UATAwnvszA/bRzfps4ncyS1AMyByfOUmczYT+/FO8PjiDiv9n3V7lU7i8esDBonbuFjlAe/BsnhLCHlEgDTicLyAZYYO0= pubkey for ansible

# ssh-copy-id insists on public key files ending in .pub
# This isn't a real key.
control_node_public_key_file: /home/nick/.ssh/ansible-key.pub
control_node_private_key_file: /home/nick/.ssh/ansible-key.priv
control_node_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  u4WOUB78GyeEsIeUSANOJwvIBlhg7QAAAAMBAAEAAAF/QqR6oyLAEP1rcZCdeoWtL3NniH
  te3CQpUqWqAreaIwSt1ieTVi/zxgJFCXaxh+QaAbzx6wXl98NvdLx6QLclOZ6IyVxrroIs
  m7BhxoLliz3amdanUY8lQY6eXL5+P/CQvZHdiP+i1it/6ypab90a0E3r2kgfNgQPRnrEZ7
  BX1Gf8FiLp4EMIe2WPivhbSxiZzyyudrym7U5ACKtGDzoGRKdI9YH15ieBAy8fpVALYPTd
  VibdkzoKrzg8QNfhi0watLRsIkzbas4jY8jcTxCSD40MZaPUDbryuWYw3yr4XWwNLSjjH1
  OPYafkGKQJ+3d07QXUMcPSnP23Xd+/HZXHdys5ibw6Vp9Gisjh27z9jJhHginT+mECJxMa
  mASut5+FBbwu0pT+rc3rZrqNeiTOBdoOoWaG/oq9Mw60jyEIMJUCvinslB5HbgSNcCffRE
  m/fOh9BA2rwiP4InW1TugBrDsBTUKHqoBxOvBC/M+zyAfXskiEMV/mYyfr6cLftqEAAADA
  Pfv8lnL+Trz6FEhAftfuc7zZr3opmy+beE1g9imA07bVMkV2QmrjvPl0/oHNDhMy6ASICN
  zEeV5QiL4rkBsMQ0KJZHleugGJRUhBsbw/kq0LhwHQs0biS9UX+r9EJJabxYB2C0VUsfzE
  ZJ52oKihEXj6CYhFyFoGg+yAwrL6ExiLjMaIuorkq6tSjI/J0a7MiiHl2I0vrvx/7VElWu
  +56mmhEXLqWgOdU+BWFaB8kQH8FabNWW5Q9EVIiPhRXX+tAAAAwQD2Wmv/yIqSIybjw7HC
  O10ZVQ17U55NQzXPI4O7KB7Sd5iDCNN7SgpW93JdAU4cexyXfHkSLXEQnrSu+58oFpvGi2
  R8qFakkh/2Y/tLuaRZdu1bVeDxQ3c8y/do4nlGUIXsc2LquouSF6fU+RHPh8AY1XpAYhjP
  Bokto5O52V6qvkGlQDEckT8gjj/ChcDua3Qy0Fc4kc8D2QQQnUIwYnPVYBefz0/yu3vVVZ
  eT+25usQ13dV03V9Vj3xfUR6C4ybUAAADBAMq+YwXbFha2hIjcjAmzlyb8ZaahSEivvzG9
  pbjo9+SunHRxfQBdPkcbsGdid043F0oi0mlFts+PcgmA9ap5pyHP28Q2Y4aQw05sOniZzO
  FYljUJyvFT7NUM40BC4+CRkcIULznIBoiY/ZDds5WAZ0FGeOtbAoZYeZGgDr0DACdH2DnO
  bVLmS4bDz3a6+NBQMSxKgg1kXMoZQlfJ+GxBeo6RyM9X9s8oG9M5XRXKw1QLGOVdGKtPXi
  0YR51E17XdWQAAABpuaWNrQGhvc3QxLmxhYi5leGFtcGxlLmNvbQEC
  -----END OPENSSH PRIVATE KEY-----


