[allowlist]
  description = "Allowlist"
  files = [
    '''ansible\.cfg$''',
    '''roles/managed_node/defaults/main\.yml$''',
    '''roles/local_repo_supplier/files/1234567890123456789-key\.pem$''',
  ]

