---
# handlers file for elk_server
- name: restart service
  ansible.builtin.systemd:
    name: "{{ app_systemd_unit }}"
    state: restarted

- name: reload service
  ansible.builtin.systemd:
    name: "{{ app_systemd_unit }}"
    state: reloaded


- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: reload logstash
  ansible.builtin.systemd:
    name: logstash
    state: reloaded


