= libvirt_net

Create linux bridges and associated libvirt network config. 

One bridge is public, for traffic going in and out of Virtual Machines. 
The public network in my case is my workstation and a home network with a route to the Internet. 

The other bridge is private, for lab VMs. 
These are more isolated, but not totally private. 
They can be reached if a route to the host is added to the workstation.

The host network interface is attached to the public bridge. 
Assume a simple machine with only one ethernet port.

The network role is not the idempotent role model it shoud be. 
It can disconnect ports from an existing bridge.
Work around this with a bridge check.
If the default IPv4 interface name is pubbr0 rather than something like enp2s0f0, 
assume this work has already been done and
the bridge to the outside world already exists.

The libvirt modules are better behaved.

== Requirements


== Role Variables

Two sets - public and lab. 


== Dependencies

rhel_system_roles


== Example Playbook


== License

MIT


== Author Information

Nick.
