---

# check for a cached storage file. 
#   "/var/lib/libvirt/images/{{ fqdn }}-base.qcow2"
# don't bother reinstalling if it exists. 

# check 
# If the volume already exists, 
# assume this work has already been done.
- name: Look for the machine volume.  
  stat: 
    path: "/var/lib/libvirt/images/{{ fqdn }}-base.qcow2"
  register: r_volume
- name: "does the volume '/var/lib/libvirt/images/{{ fqdn }}-base.qcow2' already exist?"
  set_fact:
    volume_file_exists: "{{ r_volume.stat.exists | bool }}"
- debug:
    var: volume_file_exists

- include_tasks: vm-build-kickstart.yml
  when: not volume_file_exists
- include_tasks: resources.yml
  when: not volume_file_exists
- include_tasks: vm-delete.yml
  when: not volume_file_exists
