# Create bridge and nmcli connection config.
# For CLI equivalents, see comments in public-linux-bridge.yml

- name: create a bridge using rhel-system-role network
  vars:
    network_connections:
      - name: "{{ lab_nmcli_name }}"
        state: up
        type: bridge
        interface_name: "{{ lab_bridge_name }}"
        ip:
          address:
          - "{{ lab_bridge_ip_cidr }}"
        #mac: "{{ lab_bridge_mac }}"
  include_role:
    name: rhel-system-roles.network

