---
# add DNS records for a new host to Red Hat IDM
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/installing_identity_management/index
# upstream project is FreeIPA https://www.freeipa.org/page/About

- name: New record data 
  ansible.builtin.debug:
    msg: 
    - "Add A name: {{ record_a_name }}, A value: {{ record_a_value }} to zone {{ lab_domain_forward }}"
    - "Add PTR name: {{ record_ptr_name }}, PTR value: {{ record_ptr_value }} to zone {{ lab_domain_reverse }}"

- name: "Add DNS A record to id.{{ lab_domain }}"
  community.general.ipa_dnsrecord:
    ipa_host: "id.{{ lab_domain }}"
    ipa_pass: "{{ admin_password }}"
    state: present
    zone_name: "{{ lab_domain_forward }}"
    record_name: "{{ record_a_name }}"
    record_type: 'A'
    record_value: "{{ record_a_value }}"
    validate_certs: false

- name: "Add DNS PTR record to id.{{ lab_domain }}"
  community.general.ipa_dnsrecord:
    ipa_host: "id.{{ lab_domain }}"
    ipa_pass: "{{ admin_password }}"
    state: present
    zone_name: "{{ lab_domain_reverse }}"
    record_name: "{{ record_ptr_name }}"
    record_type: 'PTR'
    record_value: "{{ record_ptr_value }}"
    validate_certs: false
