---
# Create a bridge, attach the default interface, and add libvirt config.
# Assume a simple machine with only one ethernet port.
#
# The network role is not the idempotent role model it shoud be. 
# It can disconnect ports from an existing bridge.
# Work around this with a bridge check.
# If the default IPv4 interface name is brpublic0 rather than something like enp2s0f0, 
# assume this work has already been done and
# the bridge to the outside world already exists.
#
# The libvirt modules are better behaved.
 
- name: find the default network interface name
  set_fact:
    ethernet_port: "{{ ansible_facts['default_ipv4']['interface'] }}"
- debug: 
    var: ethernet_port

- name: "define the public bridge {{ public_bridge_name }}"
  include_tasks: public-linux-bridge.yml
  when: ethernet_port != public_bridge_name

- name: "define the libvirt network {{ public_libvirt_name }}"
  include_tasks: public-libvirt-net.yml


