---
# tasks file 

- name: required packages
  ansible.builtin.dnf:
    name: cockpit
    state: latest

- name: Start the sysadmin console 'cockpit' if a request comes in
  ansible.builtin.systemd_service:
    name: cockpit.socket
    state: started
    enabled: true
