---
# handlers file for dhcp_server
  - name: restart service
    ansible.builtin.systemd:
      name: "{{ app_unit }}"
      state: restarted

  - name: reload service
    ansible.builtin.systemd:
      name: "{{ app_unit }}"
      state: reloaded


