---
# add DNS records to Red Hat IDM
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/installing_identity_management/index
# upstream project is FreeIPA https://www.freeipa.org/page/About

- name: Ensure dns A record is present
  community.general.ipa_dnsrecord:
    ipa_host: "id.{{ lab_domain }}"
    ipa_pass: "{{ admin_password }}"
    state: present
    zone_name: "{{ lab_forward_zone }}"
    record_name: "{{ item }}"
    record_type: 'A'
    record_value: "{{ address[item]['ipv4'] }}"
  loop: "{{ address | list }}"

- name: Ensure dns PTR record is present
  community.general.ipa_dnsrecord:
    ipa_host: "id.{{ lab_domain }}"
    ipa_pass: "{{ admin_password }}"
    state: present
    zone_name: "{{ lab_reverse_zone }}"
    record_name: "{{ address[item]['ip_last_octet'] }}"
    record_type: 'PTR'
    record_value: "{{ item + '.' + lab_domain }}."
  loop: "{{ address | list }}"
