---
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/deploying_web_servers_and_reverse_proxies/index#configuring-the-squid-caching-proxy-server_deploying-web-servers-and-reverse-proxies
#
# tasks file for squid_proxy
#
- name: Copy service config
  ansible.builtin.copy:
    src: "{{ app_config }}"
    dest: /etc/squid/
    owner: root
    group: squid
    mode: '0640'
  notify: restart service

# systemd
- name: Start the daemon
  ansible.builtin.systemd:
    name: "{{ app_systemd_unit }}"
    state: started
    enabled: true

# firewalld
- name: Permit service traffic
  ansible.posix.firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  loop: "{{ app_fw_services }}"

- name: Permit port traffic
  ansible.posix.firewalld:
    port: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  loop: "{{ app_fw_ports }}"
  when: app_fw_ports is defined
