---
#
# !!! Red Hat supplies roles for this. 
# see
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/installing_identity_management/index#installing-the-ansible-freeipa-package_server-ansible
#
# bombs out if already installed
# !!! check? 
# /usr/bin/ipa --version
- name: run installer
  ansible.builtin.shell:
    cmd: >
      ipa-server-install  
      --ds-password='Password;1' 
      --admin-password='Password;1' 
      --domain=lab.example.com 
      --realm=LAB.EXAMPLE.COM 
      --hostname=id.lab.example.com 
      --setup-dns 
      --forwarder={{ lab_net_prefix }}.3 
      --no-dnssec-validation 
      --auto-reverse  
      --netbios-name=LAB 
      --unattended
  ignore_errors: yes
  register: r_install

- debug: 
    var: r_install
 

# firewall
#
- name: permit service traffic
  ansible.posix.firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  loop: "{{ app_fw_services }}"

- name: permit port traffic
  ansible.posix.firewalld:
    port: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  loop: "{{ app_fw_ports }}"
  when: app_fw_ports is defined

