- name: cache the storage file
  ansible.builtin.copy:
      src: "/var/lib/libvirt/images/{{ fqdn }}.qcow2"
      remote_src: yes
      dest: "/var/lib/libvirt/images/{{ fqdn }}-base.qcow2"
      owner: qemu
      group: qemu
      mode: '0644'

- name: create a directory for machine config
  ansible.builtin.file:
    path: ~/libvirt
    state: directory

# !!! register stdout then dump to remote file
- name: store machine config
  ansible.builtin.shell:
    cmd: "virsh dumpxml {{ fqdn }} > ~/libvirt/{{ fqdn }}.xml"
    chdir: ~/libvirt
    # always overwrite this file
    #creates: "~/libvirt/{{ fqdn }}.xml"
