---
# https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_module.html
- name: stop the VM
  community.libvirt.virt:
    name: "{{ fqdn }}"
    state: shutdown

# check
# These tasks use libvirt only.
# They don't check anything at the OS level, such as waiting for a connection. 

- name: get domain info
  community.libvirt.virt:
    name: "{{ fqdn }}"
    command: info
  register: r_domain_info

- name: display domain info
  debug:
    var: r_domain_info[fqdn]

