---
# defaults file 
admin_password: 'Password;1'

lab_net_prefix: "192.168.134"
lab_mac_prefix: "52:54:00:02"
lab_domain: lab.example.com
lab_reverse_zone: "134.168.192.in-addr.arpa"
# to list keys of this dict of dicts in a loop, use: 
#       loop: "{{ address | list }}"
address:
  gateway:
    mac: "{{ lab_mac_prefix }}:00:03"
    ip_last_octet: "3"
    ipv4: "{{ lab_net_prefix + '.3' }}"
  ipsal:
    mac: "{{ lab_mac_prefix }}:00:04"
    ip_last_octet: "4"
    ipv4: "{{ lab_net_prefix + '.4' }}"
  id:
    mac: "{{ lab_mac_prefix }}:00:05"
    ip_last_octet: "5"
    ipv4: "{{ lab_net_prefix  + '.5' }}"
  message:
    mac: "{{ lab_mac_prefix }}:00:06"
    ip_last_octet: "6"
    ipv4: "{{ lab_net_prefix  + '.6' }}"
  monitor:
    mac: "{{ lab_mac_prefix }}:00:07"
    ip_last_octet: "7"
    ipv4: "{{ lab_net_prefix  + '.7' }}"
  git:
    mac: "{{ lab_mac_prefix }}:00:08"
    ip_last_octet: "8"
    ipv4: "{{ lab_net_prefix  + '.8' }}"

