---
# https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html

- name: "use gateway {{ lab_net_prefix }}.3 as the DNS server"
  community.general.nmcli:
    conn_name: enp1s0
    type: ethernet
    dns4:
    - "{{ lab_net_prefix }}.3"
    state: present

- name: brings up the interface to load change
  command: 
    cmd: "nmcli con up enp1s0"
  register: r_up
- debug:
    var: r_up