---

- name: Check before
  ansible.builtin.include_tasks: check_before.yml
- name: Trust the hypervisor's CA certificate
  ansible.builtin.include_tasks: trust_ca.yml
- name: Create a new server cert signed by the CA cert
  ansible.builtin.include_tasks: server_cert.yml
