---
# stop a network
- community.libvirt.virt_net:
    command: destroy
    name: "{{ lab_libvirt_name }}"
 
# delete a network
- community.libvirt.virt_net:
    state: absent
    name: "{{ lab_libvirt_name }}"
 
