---
# tasks file

# Create a linux bridge, then matching libvirt config.
# This way does not add dnsmasq.
#
# If the lab bridge is already active, 
# assume this work has already been done.
- name: Look for this lab bridge device.  
  debug: 
    var: lab_bridge_name
- name: is the bridge active
  set_fact:
    lab_bridge_active: "{{ ansible_facts[lab_bridge_name]['active'] | default('false') | bool }}"

- name: "define the lab bridge {{ lab_bridge_name }}"
  include_tasks: lab-linux-bridge.yml
  when: not lab_bridge_active

- name: "define the libvirt network {{ lab_libvirt_name }}"
  include_tasks: lab-libvirt-net.yml

