---
# https://www.elastic.co/guide/en/logstash/8.5/installing-logstash.html

- name: "logstash: install supporting packages"
  yum:
    name: python3-libsemanage

- name: "logstash: import the Elastic GPG Key"
  ansible.builtin.rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: "logstash: copy yum repo file"
  ansible.builtin.copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: "logstash: install packages"
  ansible.builtin.dnf:
    name: 
    - logstash
    enablerepo: elasticsearch
  register: r_dnf_logstash

- debug:
    var: r_dnf_logstash



# config
- name: "logstash: copy server config"
  ansible.builtin.copy:
    src: logstash.yml
    dest: /etc/logstash/
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: "logstash: copy pipeline config"
  ansible.builtin.copy:
    src: logstash-syslog.conf
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  notify: restart logstash


# systemd
- name: "logstash: start the daemon"
  vars:
    app_systemd_unit: logstash
  ansible.builtin.systemd:
    name: "{{ app_systemd_unit }}"
    state: started
    enabled: yes

# firewall
# !!!
#

# tests 
# sudo -u logstash /usr/share/logstash/bin/logstash --path.settings /etc/logstash -t
#
