---
# tasks file for elk_server
# 
# https://www.elastic.co/guide/en/elastic-stack/current/installing-elastic-stack.html
# Install the Elastic Stack products you want to use in the following order:
#
# Elasticsearch 
#   https://www.elastic.co/guide/en/elasticsearch/reference/8.5/install-elasticsearch.html
#   https://www.elastic.co/guide/en/elasticsearch/reference/8.5/rpm.html
# Kibana 
#   https://www.elastic.co/guide/en/kibana/8.5/install.html
#   https://www.elastic.co/guide/en/kibana/8.5/rpm.html
# Logstash (install)
# Beats (install instructions)
# APM (install instructions)
# Elasticsearch Hadoop (install instructions)

- include_tasks: elasticsearch.yml
- include_tasks: kibana.yml
- include_tasks: logstash.yml

