---
# tasks file 

# check 
# If status check passes, 
# assume this server is already registered to insights.
- name: "{{ fqdn }} already registered to insights? "
  ansible.builtin.command: 
    cmd: /usr/bin/insights-client --status
  register: r_ic_status
  ignore_errors: yes
- name: "registered?"
  ansible.builtin.set_fact:
    f_ic_registered: "{{ not r_ic_status.failed }}"
- ansible.builtin.debug:
    var: f_ic_registered


# !!! many failures trying to use 
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhel_system_roles/content/role/rhc/
- name: "Register this system with Red Hat Insights"
  ansible.builtin.shell:
    cmd: insights-client --register
  when: not f_ic_registered
