---
# tasks file for hosts_record

- name: "add to /etc/hosts: {{ ip_address }}   {{ fqdn }}   {{ host }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ fqdn }}"
    line: "{{ ip_address }}   {{ fqdn }}   {{ host }}"
