---
# tasks file for hosts_record

- name: "add to /etc/hosts: {{ h_ip_address }}   {{ h_fqdn }}   {{ h_host }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ h_fqdn }}"
    line: "{{ h_ip_address }}   {{ h_fqdn }}   {{ h_host }}"
