---
# tasks file for hosts_record

- name: "add to /etc/hosts: {{ hosts_record_conf['ip_address'] }}   {{ hosts_record_conf['fqdn'] }}   {{ hosts_record_conf['host'] }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ hosts_record_conf['fqdn'] }}"
    line: "{{ hosts_record_conf['ip_address'] }}   {{ hosts_record_conf['fqdn'] }}   {{ hosts_record_conf['host'] }}"
