---
# tasks file for hosts_record

- name: add a line to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ fqdn }}"
    line: "{{ ip_address }}   {{ fqdn }}   {{ host }}"
