= libvirt_machine, an Ansible role

Create a libvirt domain.


The role creates a KVM guest, installs RHEL 9.0 (minimal), configures a few things then powers off (the VM should reboot, but a QEMU option prevents that).
This role is simple, with plenty of hardcoded values in both the tasks and kickstart file _templates/kvm-guest.ks.j2_. 
I made this role to learn more about the libvirt collection so don't expect polish.

The role creates libvirt resources.
Resources are labelled with the FQDN. 
If the name is kvm-guest.lab.example.com, you get these. 

* kvm-guest.lab.example.com - a libvirt domain defined from an XML file ~/libvirt/kvm-guest.xml
* kvm-guest.lab.example.com.qcow2 - disk volume file, copied from kvm-guest.lab.example.com-base.qcow2



== Requirements

disk image kvm-guest.lab.example.com-base.qcow2

XML file ~/libvirt/kvm-guest.xml

The libvirt environment installed and running (see https://github.com/nickhardiman/libvirt-host).

Installer ISO file _/var/lib/libvirt/images/rhel-baseos-9.0-x86_64-dvd.iso_.
Add other versions you might want to install, like _rhel-8.6-x86_64-dvd.iso_. 
Download ISO files from https://access.redhat.com/downloads/. 
Sign up for free at https://developers.redhat.com/ to get access.

Enough free disk space to hold ISOs and the new storage volume (30GiB by default). 


== Role Variables

For configurable values, see 
https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml.


== Dependencies

community.libvirt (https://github.com/ansible-collections/community.libvirt)


== Example with playbook

Create a playbook. 
There's a pretty complicated one here. 
https://github.com/nickhardiman/ansible-playbook-lab

Create another VM called _another-vm_ with a bigger disk (40GiB, not 30) and a different MAC address.
```
sudo ansible-playbook libvirt-guest/tests/test.yml  \
    --extra-var="host=another-vm"  \
	--extra-var="disk_size=40"   \
	--extra-var="if1_mac=52:54:00:12:34:56"
```
Delete _another-vm_.
```
sudo ansible-playbook libvirt-guest/tests/no-kvm-guest.yml \
    --extra-var="host=another-vm" 
```
Install RHEL 8, not 9.
```
sudo ansible-playbook libvirt-guest/tests/test.yml  \
    --extra-var="os_variant=rhel8.5"  \
    --extra-var="install_iso=/var/lib/libvirt/images/rhel-8.6-x86_64-dvd.iso"
```



== A fiddly example  

Create the VM. 

```
git clone https:/github.com/nickhardiman/ansible-collection-platform.git
sudo ANSIBLE_COLLECTIONS_PATHS=.:~/.ansible/collections:/usr/share/ansible/collections ansible-playbook roles/libvirt_volume/tests/test.yml
sudo ANSIBLE_COLLECTIONS_PATHS=.:~/.ansible/collections:/usr/share/ansible/collections ansible-playbook roles/libvirt_machine/tests/test.yml
```

Remove the VM.

```
sudo ANSIBLE_COLLECTIONS_PATHS=.:~/.ansible/collections:/usr/share/ansible/collections ansible-playbook roles/libvirt_machine/tests/no-kvm-guest.yml
```

== License

BSD

== Author Information

Nick Hardiman

